version: '3.8'

services:
  app:
    build: .
    container_name: My_Portfolio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: sh -c "node fetch.js && npm start"
